version: '3.2'

services:
  app:
    build: ./docker
    depends_on:
      - db
    volumes:
      - ./src:/var/www/app/
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
